language: python
python:
  - "3.10"

branches:
  only:
    - main

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install black flake8 coverage coveralls

script:
  # 1️⃣ code formatting check
  - black --check .
  # 2️⃣ linting check
  - flake8 .
  # 3️⃣ run test suite + coverage
  - coverage run manage.py test

after_success:
  - coveralls

before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 travis_key
  - ssh-add travis_key

deploy:
  provider: script
  script: bash deploy_ec2.sh
  on:
    branch: main
